"""Symmetric encryption for user-supplied secrets (Maxi credentials).

Why Fernet: it's the OWASP-recommended primitive in the cryptography
package for "encrypt a small string at rest". AES-128-CBC + HMAC-SHA256,
versioned output, trivial API.

Key management: we read ``settings.MAXI_CRED_KEY`` (base64-encoded
32-byte key). If absent on startup, we generate one and write it to the
``.env`` file so the next boot finds it. The key never leaves the server.

⚠️  Losing the key means the stored credentials are unrecoverable.
Back up ``.env`` alongside ``batchchef.db``.
"""
from __future__ import annotations
import logging
from pathlib import Path

from cryptography.fernet import Fernet

from app.config import settings

logger = logging.getLogger(__name__)


_fernet: Fernet | None = None


def _dotenv_path() -> Path:
    """Resolve the backend's .env file. We write the generated key there on
    first boot so subsequent runs re-use it."""
    # backend/app/utils/crypto.py → backend/.env
    return Path(__file__).parent.parent.parent / ".env"


def _ensure_key() -> bytes:
    """Return the configured Fernet key; generate+persist one if missing."""
    key = getattr(settings, "MAXI_CRED_KEY", None)
    if key:
        return key.encode() if isinstance(key, str) else key

    # Generate + write to .env for persistence across reboots
    new_key = Fernet.generate_key()
    env_path = _dotenv_path()
    line = f"\nMAXI_CRED_KEY={new_key.decode()}\n"
    try:
        if env_path.exists():
            with env_path.open("a", encoding="utf-8") as f:
                f.write(line)
        else:
            env_path.write_text(f"# Auto-generated by app/utils/crypto.py{line}", encoding="utf-8")
        logger.warning(
            "Generated new MAXI_CRED_KEY and appended to %s. "
            "Back it up alongside batchchef.db — losing this key means user "
            "Maxi credentials become unrecoverable.",
            env_path,
        )
    except OSError as e:
        logger.error("Could not write .env — key is only valid for this process: %s", e)
    return new_key


def _cipher() -> Fernet:
    global _fernet
    if _fernet is None:
        _fernet = Fernet(_ensure_key())
    return _fernet


def encrypt(plaintext: str) -> str:
    """Return base64 Fernet token of ``plaintext``."""
    if plaintext is None:
        raise ValueError("Cannot encrypt None")
    return _cipher().encrypt(plaintext.encode("utf-8")).decode("ascii")


def decrypt(token: str) -> str:
    """Reverse of ``encrypt``. Raises ``InvalidToken`` on tampering or wrong key."""
    return _cipher().decrypt(token.encode("ascii")).decode("utf-8")


def ensure_secret_key() -> str:
    """Make sure ``settings.SECRET_KEY`` is a strong random value. Generate +
    persist to .env on first boot if empty. Returns the effective key.

    Called from app startup (``main.lifespan``). Solves the audit finding
    that SECRET_KEY had a weak default hardcoded in config.py — shipping
    that default would mean anyone with read access to the repo can forge
    JWTs."""
    import secrets as _secrets
    if settings.SECRET_KEY:
        return settings.SECRET_KEY

    new = _secrets.token_urlsafe(48)
    env_path = _dotenv_path()
    line = f"\nSECRET_KEY={new}\n"
    try:
        if env_path.exists():
            with env_path.open("a", encoding="utf-8") as f:
                f.write(line)
        else:
            env_path.write_text(f"# Auto-generated{line}", encoding="utf-8")
        logger.warning(
            "Generated new SECRET_KEY and appended to %s. BACK IT UP with "
            "batchchef.db — rotating it invalidates all existing JWTs "
            "(users have to re-login).",
            env_path,
        )
    except OSError as e:
        logger.error("Could not persist SECRET_KEY to .env: %s. Using in-memory only.", e)

    # Mutate the settings singleton so downstream imports see the new value
    settings.SECRET_KEY = new
    return new
