"""initial

Revision ID: 61bc335b03d5
Revises: 
Create Date: 2026-04-20 14:41:34.890209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bc335b03d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('target_portions', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_estimated_cost', sa.Float(), nullable=True),
    sa.Column('total_portions', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('current_item', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('display_name_fr', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('is_produce', sa.Boolean(), nullable=False),
    sa.Column('default_unit', sa.String(), nullable=True),
    sa.Column('estimated_price_per_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_master_canonical_name'), ['canonical_name'], unique=True)

    op.create_table('recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marmiton_url', sa.String(), nullable=False),
    sa.Column('marmiton_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('is_sweet', sa.Boolean(), nullable=False),
    sa.Column('is_salty', sa.Boolean(), nullable=False),
    sa.Column('is_spicy', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('cuisine_type', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('calories_per_portion', sa.Float(), nullable=True),
    sa.Column('proteins_per_portion', sa.Float(), nullable=True),
    sa.Column('carbs_per_portion', sa.Float(), nullable=True),
    sa.Column('lipids_per_portion', sa.Float(), nullable=True),
    sa.Column('estimated_cost_per_portion', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('ai_processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_marmiton_url'), ['marmiton_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_recipe_slug'), ['slug'], unique=False)

    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('store_location_id', sa.String(), nullable=True),
    sa.Column('is_transactional', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('batch_recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_master_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('quantity_per_portion', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_master_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.create_index('ix_ri_ingredient', ['ingredient_master_id'], unique=False)
        batch_op.create_index('ix_ri_recipe', ['recipe_id'], unique=False)

    op.create_table('store_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_master_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('format_qty', sa.Float(), nullable=True),
    sa.Column('format_unit', sa.String(), nullable=True),
    sa.Column('calories_per_100', sa.Float(), nullable=True),
    sa.Column('proteins_per_100', sa.Float(), nullable=True),
    sa.Column('carbs_per_100', sa.Float(), nullable=True),
    sa.Column('lipids_per_100', sa.Float(), nullable=True),
    sa.Column('nutriscore', sa.String(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_price_change_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_master_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_master_id', 'store_id', 'sku', name='uq_product_store_sku')
    )
    with op.batch_alter_table('store_product', schema=None) as batch_op:
        batch_op.create_index('ix_sp_ingredient', ['ingredient_master_id'], unique=False)
        batch_op.create_index('ix_sp_store', ['store_id'], unique=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_master_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source_store_product_id', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_master_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['source_store_product_id'], ['store_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_scan_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('ingredient_master_id', sa.Integer(), nullable=True),
    sa.Column('matched_store_product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_master_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['matched_store_product_id'], ['store_product.id'], ),
    sa.ForeignKeyConstraint(['receipt_scan_id'], ['receipt_scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_master_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('store_product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_needed', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('format_qty', sa.Float(), nullable=True),
    sa.Column('format_unit', sa.String(), nullable=True),
    sa.Column('packages_to_buy', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('from_inventory_qty', sa.Float(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_master_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_master_id', sa.Integer(), nullable=False),
    sa.Column('change_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('source_ref_type', sa.String(), nullable=True),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_master_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_movement')
    op.drop_table('shopping_list_item')
    op.drop_table('receipt_item')
    op.drop_table('price_history')
    op.drop_table('inventory_item')
    with op.batch_alter_table('store_product', schema=None) as batch_op:
        batch_op.drop_index('ix_sp_store')
        batch_op.drop_index('ix_sp_ingredient')

    op.drop_table('store_product')
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_index('ix_ri_recipe')
        batch_op.drop_index('ix_ri_ingredient')

    op.drop_table('recipe_ingredient')
    op.drop_table('receipt_scan')
    op.drop_table('batch_recipe')
    op.drop_table('store')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_slug'))
        batch_op.drop_index(batch_op.f('ix_recipe_marmiton_url'))

    op.drop_table('recipe')
    with op.batch_alter_table('ingredient_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_master_canonical_name'))

    op.drop_table('ingredient_master')
    op.drop_table('import_job')
    op.drop_table('batch')
    # ### end Alembic commands ###
