"""add_user_auth

Revision ID: e533acb00b56
Revises: a3c7d1e2f4b5
Create Date: 2026-04-20 16:27:15.548981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e533acb00b56'
down_revision: Union[str, Sequence[str], None] = 'a3c7d1e2f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'user' not in existing_tables:
        op.create_table('user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
        sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    user_indexes = {i['name'] for i in inspector.get_indexes('user')} if 'user' in existing_tables else set()
    if 'ix_user_email' not in user_indexes:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    batch_cols = {c['name'] for c in inspector.get_columns('batch')}
    with op.batch_alter_table('batch', schema=None) as batch_op:
        if 'user_id' not in batch_cols:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_batch_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_batch_user', 'user', ['user_id'], ['id'], ondelete='SET NULL')

    ing_indexes = {i['name'] for i in inspector.get_indexes('ingredient_master')}
    with op.batch_alter_table('ingredient_master', schema=None) as batch_op:
        if 'ix_ingredient_parent' in ing_indexes:
            batch_op.drop_index(batch_op.f('ix_ingredient_parent'))
        if 'ix_ingredient_master_parent_id' not in ing_indexes:
            batch_op.create_index(batch_op.f('ix_ingredient_master_parent_id'), ['parent_id'], unique=False)

    inv_cols = {c['name'] for c in inspector.get_columns('inventory_item')}
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        if 'user_id' not in inv_cols:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_inventory_item_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_inventory_user', 'user', ['user_id'], ['id'], ondelete='SET NULL')

    rec_cols = {c['name'] for c in inspector.get_columns('receipt_scan')}
    with op.batch_alter_table('receipt_scan', schema=None) as batch_op:
        if 'user_id' not in rec_cols:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_receipt_scan_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_receipt_user', 'user', ['user_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_scan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_receipt_scan_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_item_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ingredient_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_master_parent_id'))
        batch_op.create_index(batch_op.f('ix_ingredient_parent'), ['parent_id'], unique=False)

    with op.batch_alter_table('batch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_batch_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
